imports:
    - { resource: parameters.ini }

framework:
    # esi:              ~
    secret:             WVl0RVeKI5j8M7bkDNMJadvoeV0idWwA
    charset:            UTF-8
    router:             { resource: "%kernel.root_dir%/config/routing.yml" }
    form:               true
    csrf_protection:    true
    validation:         { enabled: true, enable_annotations: true }
    templating:         { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
    translator: { fallback: en }
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     true
        name:           wed

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

## Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true



## Swiftmailer Configuration
swiftmailer:
    transport:  smtp
#    encryption: ssl
    auth_mode:  login
    host:       mail.labodadelanio.com.ar
#    transport:  gmail
    username:   sole.luks+labodadelanio.com.ar
    password:   soleluks168219
    spool:
        type: file
        path: %kernel.root_dir%/spool

## Security Configuration
security:
    encoders:
        Wed\WeddingBundle\Entity\User: plaintext

    providers:
        main:
            entity: { class: WedWeddingBundle:User, property: email }

    firewalls:
        main:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /login
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path:   /logout
                target: /login
            security: true
            anonymous: true

#    access_denied_url: /accessdeniedURL

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/guest, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /.*, roles: [ROLE_USER, ROLE_ADMIN] }