# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal


Wedding:
    resource: "@WedWeddingBundle/Resources/config/routing.yml"