_security_login:
    pattern:  /login/
    defaults: { _controller: WedWeddingBundle:Security:login }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

admin_home:
    pattern:  /admin/
    defaults: { _controller: WedWeddingBundle:Admin:index }
    
admin_edit_guest:
    pattern:  /edit/guest/{id}
    defaults: { _controller: WedWeddingBundle:Admin:editGuest, id: null }

admin_spool_emails:
    pattern:  /admin/spoolemails/
    defaults: { _controller: WedWeddingBundle:Admin:spoolEmails }

homepage:
    pattern:  /
    defaults: { _controller: WedWeddingBundle:Guest:index }

Wedding:
    pattern:  /Wedding
    defaults: { _controller: WedWeddingBundle:Wedding:index }

guest_index:
    pattern:  /guest/
    defaults: { _controller: WedWeddingBundle:Guest:index }
guest_confirmation:
    pattern:  /guest/confirmation/
    defaults: { _controller: WedWeddingBundle:Guest:confirmation }
guest_save_confirmation:
    pattern:  /guest/confirmation/save
    defaults: { _controller: WedWeddingBundle:Guest:saveConfirmation }
    requirements:
            _method:  POST
guest_choose_menu:
    pattern:  /guest/menu/
    defaults: { _controller: WedWeddingBundle:Guest:chooseMenu }
guest_save_menu:
    pattern:  /guest/menu/save
    defaults: { _controller: WedWeddingBundle:Guest:saveMenu }
    requirements:
            _method:  POST

guests_view:
    pattern:  /admin/guests/view/{id}
    defaults: { _controller: WedWeddingBundle:Admin:viewGuests, id: null }

guests_edit:
    pattern:  /admin/guests/edit/{id}
    defaults: { _controller: WedWeddingBundle:Admin:editGuest, id: null, errors: null }

guests_save:
    pattern:  /admin/guests/save/{id}
    defaults: { _controller: WedWeddingBundle:Admin:guestsSave, id: null }
    requirements:
        _method:  POST

users_list:
    pattern:  /admin/users/list/
    defaults: { _controller: WedWeddingBundle:Admin:usersList }

users_edit:
    pattern:  /admin/users/edit/{id}
    defaults: { _controller: WedWeddingBundle:Admin:editUser, id: null, errors: null }

users_save:
    pattern:  /admin/users/save/
    defaults: { _controller: WedWeddingBundle:Admin:usersSave }
    requirements:
        _method:  POST